### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jackwuwei/wav2mp3-android#1]
1. is only mp3 files supported ?
2. how come it's apache license? Isn't encoding to mp3 have a different license? If so, what is it?
3. is it possible to convert files using a stream (or url) instead of a real storage file?
4. can you please update the project to be Android-Studio friendly ? Currently it's for Eclipse...

**Comment by jackwuwei** [comment]
1. Yes, only supported convert to mp3 file.
2. Using LAME encode mp3, please read LAME license file.
3. Sure, you can fork this project and modify.
4. I convert to Andriod Studio now.
